
```{r}
sunspots_rmse <- read.csv("../../data/Univariate/sunspots_RMSE.csv")
  
colnames(sunspots_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

sunspots_rmse %>% select(-index) |>
  kable(caption = "RMSE for data imputation methods on Sunspots dataset") 

cat("\\label{tab:RMSE_sunspots}\n")

lake_rmse <- read.csv("../../data/Univariate/lake_RMSE.csv")
  
colnames(lake_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

lake_rmse %>% select(-index) |>
  kable(caption = "RMSE for data imputation methods on LakeHuron dataset") 
cat("\\label{tab:RMSE_lake}\n")
beer_rmse <- read.csv("../../data/Univariate/beer_RMSE.csv")
  
colnames(beer_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

sunspots_rmse %>% select(-index) |>
  kable(caption = "RMSE for data imputation methods on Beer dataset") 
cat("\\label{tab:RMSE_beer}\n")

lynx_rmse <- read.csv("../../data/Univariate/lynx_RMSE.csv")
  
colnames(lynx_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

lynx_rmse %>% select(-index) |>
  kable(caption = "RMSE for data imputation methods on Lynx dataset") 
cat("\\label{tab:RMSE_lynx}\n")
```
```{r}
library(knitr)
library(kableExtra)
library(dplyr)

# Read and process Sunspots data
sunspots_rmse <- read.csv("../../data/Univariate/sunspots_RMSE.csv")
colnames(sunspots_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

sunspots_rmse %>% 
  select(-index) %>%
  kable(caption = "RMSE for data imputation methods on Sunspots dataset", format = "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped") 

knitr::asis_output("\\label{tab:RMSE_sunspots}")

# Read and process Lake Huron data
lake_rmse <- read.csv("../../data/Univariate/lake_RMSE.csv")
colnames(lake_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

lake_rmse %>% 
  select(-index) %>%
  kable(caption = "RMSE for data imputation methods on Lake Huron dataset", format = "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped") 

knitr::asis_output("\\label{tab:RMSE_lake}")

# Read and process Beer data
beer_rmse <- read.csv("../../data/Univariate/beer_RMSE.csv")
colnames(beer_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

beer_rmse %>% 
  select(-index) %>%
  kable(caption = "RMSE for data imputation methods on Beer dataset", format = "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped") 

knitr::asis_output("\\label{tab:RMSE_beer}")

# Read and process Lynx data
lynx_rmse <- read.csv("../../data/Univariate/lynx_RMSE.csv")
colnames(lynx_rmse) <- c("index", "Missing percentage", "LOCF RMSE", "Mean Imputation RMSE", "Linear Interpolation RMSE", "Kalman RMSE")

lynx_rmse %>% 
  select(-index) %>%
  kable(caption = "RMSE for data imputation methods on Lynx dataset", format = "latex", booktabs = TRUE) %>%
  kable_styling(latex_options = "striped") 

knitr::asis_output("\\label{tab:RMSE_lynx}")

```

