---
title: "Missing Data Imputation Methods for Univariate and Multivariate Time Series"
author: "Jacob Clinton George Smith-Kolff"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    number_sections: true
    fig_caption: true
    keep_tex: true

header-includes:
    - \usepackage[colorinlistoftodos]{todonotes}
    - \usepackage{graphicx}
    - \usepackage{float}
    - \usepackage{hyperref}
    - \usepackage{appendix} 
    - \usepackage{caption}
    - \usepackage{subfigure}
    - \usepackage{biblatex}
    - \usepackage{titlesec}
    - \titleformat{\chapter}[hang]{\normalfont\huge\bfseries}{\thechapter}{20pt}{\Huge}
    - \setcounter{secnumdepth}{2}
documentclass: report
bibliography: references.bib
csl: ieee.csl
geometry: margin=1.3in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(bookdown)
rm(list=ls())
```



```{r child='Chapters/1-Introduction.Rmd'}
```

```{r child='Chapters/2-Theory.Rmd'}
```

```{r child='Chapters/3-Illustration.Rmd'}
```

```{r child='Chapters/4-Conclusion.Rmd'}
```

# References

<div id="refs"></div>


```{r child='Chapters/5-Appendix.Rmd'}
```








